# Generated by Django 2.2.14 on 2020-07-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '歷史紀錄', 'verbose_name_plural': '歷史紀錄'},
        ),
    ]
