# Generated by Django 2.2.14 on 2020-09-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200731_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='群組名')),
            ],
            options={
                'verbose_name': '推播群組',
                'verbose_name_plural': '推播群組',
            },
        ),
        migrations.AlterModelOptions(
            name='accesstoken',
            options={'verbose_name': '推播用戶', 'verbose_name_plural': '推播用戶'},
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='創建日期'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='groups',
            field=models.ManyToManyField(to='api.BroadcastGroup', verbose_name='群組'),
        ),
    ]
