# Generated by Django 2.2.14 on 2020-09-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200902_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='toGroup',
            field=models.CharField(default='全部', max_length=20, verbose_name='推播至'),
        ),
    ]
